remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://silviaporciuleanu.github.io"
title: "Silvia Porciuleanu"
description: "PhD researcher in political science at the European University Institute"

logo: /assets/images/IMG_8438.jpeg
show_downloads: false

email: silvia.porciuleanu@eui.eu
cv: /CV_Porciuleanu_Silvia.pdf
bluesky: https://bsky.app/profile/silviaporciuleanu.bsky.social
linkedin: https://www.linkedin.com/in/silvia-porciuleanu/
github_url: https://github.com/SilviaPorciuleanu
